sudo: required
services:
  - docker


before_install:
  - docker build -t alexanderbudnikov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexanderbudnikov/react-test npm test

after_success:
  - docker build -t alexanderbudnikov/multi-client ./client
  - docker build -t alexanderbudnikov/multi-nginx ./nginx
  - docker build -t alexanderbudnikov/multi-server ./server
  - docker build -t alexanderbudnikov/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alexanderbudnikov/multi-client
  - docker push alexanderbudnikov/multi-nginx
  - docker push alexanderbudnikov/multi-server
  - docker push alexanderbudnikov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: eelasticbeanstalk-us-east-1-07119272119
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
